inherit_from:
    - .rubocop_todo.yml
    - .rubocop-performance.yml
    - .rubocop-rails.yml
    - .rubocop-performance.yml
    - .rubocop-rails.yml

    - .rubocop-performance.yml
    - .rubocop-rails.yml

    # .rubocop.yml

    # The behavior of RuboCop can be controlled via the .rubocop.yml
    # configuration file. It makes it possible to enable/disable
    # certain cops (checks) and to alter their behavior if they accept
    # any parameters. The file can be placed either in your home
    # directory or in some project directory.
    #
    # RuboCop will start looking for the configuration file in the directory
    # where the inspected file is and continue its way up to the root directory.
    #

    - ".rubocop-performance.yml"
    - ".rubocop-rails.yml"

require:
    - rubocop-performance
    - rubocop-rails
    - rubocop-rspec

AllCops:
    TargetRubyVersion: 2.7
    TargetRailsVersion: 6.0
    Exclude:
        - "**/db/migrate/*"
        - "db/schema.rb"
        - "**/Gemfile.lock"
        - "**/Rakefile"
        - "**/rails"
        - "**/vendor/**/*"
        - "**/spec_helper.rb"
        - "node_modules/**/*"
        - "bin/*"
        - "config/**/*"

###########################################################
###################### RuboCop ############################
###########################################################

# You can find all configuration options for rubocop here: https://docs.rubocop.org/rubocop/cops_bundler.html

###########################################################
####################### Gemspec ###########################
###########################################################

Gemspec/DeprecatedAttributeAssignment: # (new in 1.10)
    Enabled: true

###########################################################
######################## Layout ###########################
###########################################################

Layout/ClassStructure:
    ExpectedOrder:
        - module_inclusion
        - constants
        - association
        - public_attribute_macros
        - public_delegate
        - macros
        - initializer
        - public_class_methods
        - public_methods
        - protected_attribute_macros
        - protected_methods
        - private_attribute_macros
        - private_delegate
        - private_methods

Layout/IndentationWidth:
    Width: 2

Layout/EmptyLineAfterMultilineCondition:
    Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
    Enabled: true

Layout/EndOfLine:
    Enabled: false

Layout/FirstArrayElementIndentation:
    EnforcedStyle: consistent

Layout/FirstArrayElementLineBreak:
    Enabled: true

Layout/FirstHashElementIndentation:
    EnforcedStyle: consistent

Layout/FirstHashElementLineBreak:
    Enabled: true

Layout/LineEndStringConcatenationIndentation: # (new in 1.18)
    Enabled: true

Layout/LineLength:
    Max: 150
    Exclude:
        - "**/spec/**/*"

Layout/MultilineArrayBraceLayout:
    EnforcedStyle: new_line

Layout/MultilineOperationIndentation:
    EnforcedStyle: indented

Layout/MultilineHashBraceLayout:
    EnforcedStyle: new_line

Layout/MultilineHashKeyLineBreaks:
    Enabled: true

Layout/MultilineMethodCallBraceLayout:
    EnforcedStyle: new_line

Layout/MultilineMethodDefinitionBraceLayout:
    EnforcedStyle: new_line

Layout/SpaceAroundMethodCallOperator:
    Enabled: true

Layout/SpaceBeforeBrackets: # (new in 1.7)
    Enabled: true

Layout/SpaceInLambdaLiteral:
    EnforcedStyle: require_space

###########################################################
######################## Lint #############################
###########################################################

Lint/AmbiguousAssignment: # (new in 1.7)
    Enabled: true

Lint/AmbiguousBlockAssociation:
    Exclude:
        - "**/spec/**/*"

Lint/AssignmentInCondition:
    AllowSafeAssignment: false

Lint/BinaryOperatorWithIdenticalOperands:
    Enabled: true

Lint/DeprecatedConstants: # (new in 1.8)
    Enabled: true

Lint/DeprecatedOpenSSLConstant:
    Enabled: true

Lint/DuplicateBranch: # (new in 1.3)
    Enabled: true

Lint/DuplicateElsifCondition:
    Enabled: true

Lint/DuplicateRegexpCharacterClassElement: # (new in 1.1)
    Enabled: true

Lint/DuplicateRequire:
    Enabled: true

Lint/DuplicateRescueException:
    Enabled: true

Lint/EmptyBlock: # (new in 1.1)
    Enabled: true

Lint/EmptyClass: # (new in 1.3)
    Enabled: true

Lint/EmptyConditionalBody:
    Enabled: true

Lint/EmptyFile:
    Enabled: true

Lint/EmptyInPattern: # (new in 1.16)
    Enabled: true

Lint/FloatComparison:
    Enabled: true

Lint/LambdaWithoutLiteralBlock: # (new in 1.8)
    Enabled: true

Lint/MissingSuper:
    Enabled: true

Lint/MixedRegexpCaptureTypes:
    Enabled: true

Lint/NoReturnInBeginEndBlocks: # (new in 1.2)
    Enabled: true

Lint/NumberConversion:
    Enabled: true

Lint/NumberedParameterAssignment: # (new in 1.9)
    Enabled: true

Lint/OrAssignmentToConstant: # (new in 1.9)
    Enabled: true

Lint/RaiseException:
    Enabled: true

Lint/RedundantDirGlobSort: # (new in 1.8)
    Enabled: true

Lint/SelfAssignment:
    Enabled: true

Lint/SymbolConversion: # (new in 1.9)
    Enabled: true

Lint/ToEnumArguments: # (new in 1.1)
    Enabled: true

Lint/TrailingCommaInAttributeDeclaration:
    Enabled: true

Lint/TripleQuotes: # (new in 1.9)
    Enabled: true

Lint/UnexpectedBlockArity: # (new in 1.5)
    Enabled: true

Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
    Enabled: true

Lint/UnusedBlockArgument:
    IgnoreEmptyBlocks: false

Lint/UnusedMethodArgument:
    IgnoreEmptyMethods: false

Lint/UselessMethodDefinition:
    Enabled: true

###########################################################
######################## Metric ###########################
###########################################################

Metrics/AbcSize:
    Max: 45

Metrics/BlockLength:
    CountComments: false
    Max: 60
    Exclude:
        - "**/spec/**/*"
        - "**/*.rake"
        - "**/factories/**/*"
        - "**/config/routes.rb"

Metrics/ClassLength:
    CountAsOne: ["array", "hash"]
    Max: 150

Metrics/CyclomaticComplexity:
    Max: 10

Metrics/MethodLength:
    CountAsOne: ["array", "hash"]
    Max: 30

Metrics/ModuleLength:
    CountAsOne: ["array", "hash"]
    Max: 250
    Exclude:
        - "**/spec/**/*"

Metrics/ParameterLists:
    Exclude:
        - "**/spec/feature/*"

Metrics/PerceivedComplexity:
    Max: 10

###########################################################
######################## Naming ###########################
###########################################################

Naming/ConstantName:
  Enabled: true

Naming/InclusiveLanguage: # (new in 1.18)
  Enabled: true

Naming/PredicateName:
  Enabled: true

###########################################################
######################## Style ############################
###########################################################

Style/AccessorGrouping:
    Enabled: true

Style/ArgumentsForwarding: # (new in 1.1)
    Enabled: true

Style/ArrayCoercion:
    Enabled: true

Style/AutoResourceCleanup:
    Enabled: true

Style/BisectedAttrAccessor:
    Enabled: true

Style/CaseLikeIf:
    Enabled: true

Style/ClassAndModuleChildren:
    Enabled: false

Style/CollectionCompact: # (new in 1.2)
    Enabled: true

Style/CollectionMethods:
    Enabled: true

Style/CombinableLoops:
    Enabled: true

Style/CommandLiteral:
    EnforcedStyle: percent_x

Style/ConstantVisibility:
    Enabled: true

Style/Documentation:
    Enabled: false

Style/DocumentDynamicEvalDefinition: # (new in 1.1)
    Enabled: true

Style/EndlessMethod: # (new in 1.8)
    Enabled: true

Style/ExplicitBlockArgument:
    Enabled: true

Style/GlobalStdStream:
    Enabled: true

Style/GuardClause:
    Enabled: false

Style/HashConversion: # (new in 1.10)
    Enabled: true

Style/HashEachMethods:
    Enabled: true

Style/HashExcept: # (new in 1.7)
    Enabled: true

Style/HashLikeCase:
    Enabled: true

Style/HashTransformKeys:
    Enabled: true

Style/HashTransformValues:
    Enabled: true

Style/IfWithBooleanLiteralBranches: # (new in 1.9)
    Enabled: true

Style/ImplicitRuntimeError:
    Enabled: true

Style/InlineComment:
    Enabled: true

Style/InPatternThen: # (new in 1.16)
    Enabled: true

Style/IpAddresses:
    Enabled: true

Style/KeywordParametersOrder:
    Enabled: true

Style/MethodCallWithArgsParentheses:
    Enabled: true

Style/MissingElse:
    Enabled: false

Style/MultilineInPatternThen: # (new in 1.16)
    Enabled: true

Style/MultilineMethodSignature:
    Enabled: true

Style/NegatedIfElseCondition: # (new in 1.2)
    Enabled: true

Style/NilLambda: # (new in 1.3)
    Enabled: true

Style/OptionalBooleanParameter:
    Enabled: true

Style/QuotedSymbols: # (new in 1.16)
    Enabled: true

Style/RedundantArgument: # (new in 1.4)
    Enabled: true

Style/RedundantAssignment:
    Enabled: true

Style/RedundantBegin:
    Enabled: true

Style/RedundantFetchBlock:
    Enabled: true

Style/RedundantFileExtensionInRequire:
    Enabled: true

Style/RedundantSelfAssignment:
    Enabled: true

Style/SingleArgumentDig:
    Enabled: true

Style/StringChars: # (new in 1.12)
    Enabled: true

Style/StringConcatenation:
    Enabled: true

Style/SwapValues: # (new in 1.1)
    Enabled: true

Style/FrozenStringLiteralComment:
    Enabled: false

###########################################################
######################## RSpec ############################
###########################################################

RSpec/Rails/AvoidSetupHook: # (new in 2.4)
    Enabled: true

RSpec/ContextWording:
    Enabled: false

RSpec/ExampleLength:
    Max: 30

RSpec/IdenticalEqualityAssertion: # (new in 2.4)
    Enabled: true

RSpec/MultipleExpectations:
    Enabled: false


## New Cops
Gemspec/DevelopmentDependencies: # new in 1.44
  Enabled: true
Gemspec/RequireMFA: # new in 1.23
  Enabled: true
Layout/LineContinuationLeadingSpace: # new in 1.31
  Enabled: true
Layout/LineContinuationSpacing: # new in 1.31
  Enabled: true
Lint/AmbiguousOperatorPrecedence: # new in 1.21
  Enabled: true
Lint/AmbiguousRange: # new in 1.19
  Enabled: true
Lint/ConstantOverwrittenInRescue: # new in 1.31
  Enabled: true
Lint/DuplicateMagicComment: # new in 1.37
  Enabled: true
Lint/DuplicateMatchPattern: # new in 1.50
  Enabled: true
Lint/IncompatibleIoSelectWithFiberScheduler: # new in 1.21
  Enabled: true
Lint/MixedCaseRange: # new in 1.53
  Enabled: true
Lint/NonAtomicFileOperation: # new in 1.31
  Enabled: true
Lint/RedundantRegexpQuantifiers: # new in 1.53
  Enabled: true
Lint/RefinementImportMethods: # new in 1.27
  Enabled: true
Lint/RequireRangeParentheses: # new in 1.32
  Enabled: true
Lint/RequireRelativeSelfPath: # new in 1.22
  Enabled: true
Lint/UselessRescue: # new in 1.43
  Enabled: true
Lint/UselessRuby2Keywords: # new in 1.23
  Enabled: true
Metrics/CollectionLiteralLength: # new in 1.47
  Enabled: true
Naming/BlockForwarding: # new in 1.24
  Enabled: true
Security/CompoundHash: # new in 1.28
  Enabled: true
Security/IoMethods: # new in 1.22
  Enabled: true
Style/ArrayIntersect: # new in 1.40
  Enabled: true
Style/ComparableClamp: # new in 1.44
  Enabled: true
Style/ConcatArrayLiterals: # new in 1.41
  Enabled: true
Style/DataInheritance: # new in 1.49
  Enabled: true
Style/DirEmpty: # new in 1.48
  Enabled: true
Style/EmptyHeredoc: # new in 1.32
  Enabled: true
Style/EnvHome: # new in 1.29
  Enabled: true
Style/ExactRegexpMatch: # new in 1.51
  Enabled: true
Style/FetchEnvVar: # new in 1.28
  Enabled: true
Style/FileEmpty: # new in 1.48
  Enabled: true
Style/FileRead: # new in 1.24
  Enabled: true
Style/FileWrite: # new in 1.24
  Enabled: true
Style/MagicCommentFormat: # new in 1.35
  Enabled: true
Style/MapCompactWithConditionalBlock: # new in 1.30
  Enabled: true
Style/MapToHash: # new in 1.24
  Enabled: true
Style/MapToSet: # new in 1.42
  Enabled: true
Style/MinMaxComparison: # new in 1.42
  Enabled: true
Style/NestedFileDirname: # new in 1.26
  Enabled: true
Style/NumberedParameters: # new in 1.22
  Enabled: true
Style/NumberedParametersLimit: # new in 1.22
  Enabled: true
Style/ObjectThen: # new in 1.28
  Enabled: true
Style/OpenStructUse: # new in 1.23
  Enabled: true
Style/OperatorMethodCall: # new in 1.37
  Enabled: true
Style/RedundantArrayConstructor: # new in 1.52
  Enabled: true
Style/RedundantConstantBase: # new in 1.40
  Enabled: true
Style/RedundantCurrentDirectoryInPath: # new in 1.53
  Enabled: true
Style/RedundantDoubleSplatHashBraces: # new in 1.41
  Enabled: true
Style/RedundantEach: # new in 1.38
  Enabled: true
Style/RedundantFilterChain: # new in 1.52
  Enabled: true
Style/RedundantHeredocDelimiterQuotes: # new in 1.45
  Enabled: true
Style/RedundantInitialize: # new in 1.27
  Enabled: true
Style/RedundantLineContinuation: # new in 1.49
  Enabled: true
Style/RedundantRegexpArgument: # new in 1.53
  Enabled: true
Style/RedundantRegexpConstructor: # new in 1.52
  Enabled: true
Style/RedundantSelfAssignmentBranch: # new in 1.19
  Enabled: true
Style/RedundantStringEscape: # new in 1.37
  Enabled: true
Style/ReturnNilInPredicateMethodDefinition: # new in 1.53
  Enabled: true
Style/SelectByRegexp: # new in 1.22
  Enabled: true
Style/YAMLFileRead: # new in 1.53
  Enabled: true
Performance/ConcurrentMonotonicTime: # new in 1.12
  Enabled: true
Performance/MapMethodChain: # new in 1.19
  Enabled: true
Performance/StringIdentifierArgument: # new in 1.13
  Enabled: true
Rails/ActionControllerFlashBeforeRender: # new in 2.16
  Enabled: true
Rails/ActionControllerTestCase: # new in 2.14
  Enabled: true
Rails/ActionOrder: # new in 2.17
  Enabled: true
Rails/ActiveSupportOnLoad: # new in 2.16
  Enabled: true
Rails/CompactBlank: # new in 2.13
  Enabled: true
Rails/DangerousColumnNames: # new in 2.21
  Enabled: true
Rails/DeprecatedActiveModelErrorsMethods: # new in 2.14
  Enabled: true
Rails/DotSeparatedKeys: # new in 2.15
  Enabled: true
Rails/DuplicateAssociation: # new in 2.14
  Enabled: true
Rails/DuplicateScope: # new in 2.14
  Enabled: true
Rails/DurationArithmetic: # new in 2.13
  Enabled: true
Rails/FreezeTime: # new in 2.16
  Enabled: true
Rails/I18nLazyLookup: # new in 2.14
  Enabled: true
Rails/I18nLocaleTexts: # new in 2.14
  Enabled: false
Rails/IgnoredColumnsAssignment: # new in 2.17
  Enabled: true
Rails/MigrationClassName: # new in 2.14
  Enabled: true
Rails/RedundantActiveRecordAllMethod: # new in 2.21
  Enabled: true
Rails/RedundantPresenceValidationOnBelongsTo: # new in 2.13
  Enabled: true
Rails/RedundantTravelBack: # new in 2.12
  Enabled: true
Rails/ResponseParsedBody: # new in 2.18
  Enabled: true
Rails/RootJoinChain: # new in 2.13
  Enabled: true
Rails/RootPathnameMethods: # new in 2.16
  Enabled: true
Rails/RootPublicPath: # new in 2.15
  Enabled: true
Rails/StripHeredoc: # new in 2.15
  Enabled: true
Rails/ThreeStateBooleanColumn: # new in 2.19
  Enabled: true
Rails/ToFormattedS: # new in 2.15
  Enabled: true
Rails/ToSWithArgument: # new in 2.16
  Enabled: true
Rails/TopLevelHashWithIndifferentAccess: # new in 2.16
  Enabled: true
Rails/TransactionExitStatement: # new in 2.14
  Enabled: true
Rails/UnusedRenderContent: # new in 2.21
  Enabled: true
Rails/WhereMissing: # new in 2.16
  Enabled: true
Rails/WhereNotWithMultipleConditions: # new in 2.17
  Enabled: true
Capybara/MatchStyle: # new in 2.17
  Enabled: true
Capybara/NegationMatcher: # new in 2.14
  Enabled: true
Capybara/SpecificActions: # new in 2.14
  Enabled: true
Capybara/SpecificFinders: # new in 2.13
  Enabled: true
Capybara/SpecificMatcher: # new in 2.12
  Enabled: true
FactoryBot/AssociationStyle: # new in 2.23
  Enabled: true
FactoryBot/ConsistentParenthesesStyle: # new in 2.14
  Enabled: true
FactoryBot/FactoryAssociationWithStrategy: # new in 2.23
  Enabled: true
FactoryBot/FactoryNameStyle: # new in 2.16
  Enabled: true
FactoryBot/RedundantFactoryOption: # new in 2.23
  Enabled: true
FactoryBot/SyntaxMethods: # new in 2.7
  Enabled: false
RSpec/BeEmpty: # new in 2.20
  Enabled: true
RSpec/BeEq: # new in 2.9.0
  Enabled: true
RSpec/BeNil: # new in 2.9.0
  Enabled: true
RSpec/ChangeByZero: # new in 2.11
  Enabled: true
RSpec/ContainExactly: # new in 2.19
  Enabled: true
RSpec/DuplicatedMetadata: # new in 2.16
  Enabled: true
RSpec/EmptyMetadata: # new in 2.24
  Enabled: true
RSpec/Eq: # new in 2.24
  Enabled: true
RSpec/ExcessiveDocstringSpacing: # new in 2.5
  Enabled: true
RSpec/IndexedLet: # new in 2.20
  Enabled: true
RSpec/MatchArray: # new in 2.19
  Enabled: true
RSpec/MetadataStyle: # new in 2.24
  Enabled: true
RSpec/NoExpectationExample: # new in 2.13
  Enabled: false
RSpec/PendingWithoutReason: # new in 2.16
  Enabled: true
RSpec/ReceiveMessages: # new in 2.23
  Enabled: true
RSpec/RedundantAround: # new in 2.19
  Enabled: true
RSpec/SkipBlockInsideExample: # new in 2.19
  Enabled: true
RSpec/SortMetadata: # new in 2.14
  Enabled: true
RSpec/SpecFilePathFormat: # new in 2.24
  Enabled: true
RSpec/SpecFilePathSuffix: # new in 2.24
  Enabled: true
RSpec/SubjectDeclaration: # new in 2.5
  Enabled: true
RSpec/VerifiedDoubleReference: # new in 2.10.0
  Enabled: true
RSpec/Rails/HaveHttpStatus: # new in 2.12
  Enabled: true
RSpec/Rails/InferredSpecType: # new in 2.14
  Enabled: true
RSpec/Rails/MinitestAssertions: # new in 2.17
  Enabled: true
RSpec/Rails/NegationBeValid: # new in 2.23
  Enabled: true
RSpec/Rails/TravelAround: # new in 2.19
  Enabled: true